"""The sync runner template is generated, and drift is a build failure.

`template_sync.py` used to be a hand-maintained copy of `template_async.py`, kept
honest by a checklist item asking a human to read a 1,300-line diff. These tests
assert the machine invariant that replaced it: the committed sync template is
exactly what `scripts/gen_sync.py` produces from the async one, a hand-edit to
either half is caught, and every marker that records a genuine async/sync
difference says why it is there.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts/gen_sync.py"
ASYNC_TEMPLATE = REPO_ROOT / "src/hypergraph/runners/_shared/template_async.py"
SYNC_TEMPLATE = REPO_ROOT / "src/hypergraph/runners/_shared/template_sync.py"


def _load_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("gen_sync", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # `@dataclass` resolves annotations through sys.modules, so register first.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gen_sync = _load_generator()


def _generate(source: str, tmp_path: Path) -> str:
    """Run the real transform over ``source`` instead of the committed file."""
    stand_in = tmp_path / "template_async.py"
    stand_in.write_text(source)
    return gen_sync.generate(stand_in, SYNC_TEMPLATE)


class TestCommittedFileIsGenerated:
    def test_the_committed_sync_template_is_what_the_generator_produces(self) -> None:
        assert gen_sync.generate() == SYNC_TEMPLATE.read_text()

    def test_the_committed_sync_template_says_it_is_generated(self) -> None:
        assert SYNC_TEMPLATE.read_text().startswith("# @generated by scripts/gen_sync.py")

    def test_check_passes_on_a_clean_tree(self) -> None:
        result = subprocess.run([sys.executable, str(GENERATOR), "--check"], capture_output=True, text=True)
        assert result.returncode == 0, result.stderr


class TestDriftIsCaught:
    def test_a_hand_edit_to_the_generated_file_fails_check_with_the_hunk(
        self,
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        hand_edited = SYNC_TEMPLATE.read_text().replace(
            '"""Shared sync runner lifecycle template."""',
            '"""Hand-edited."""',
            1,
        )
        assert '"""Hand-edited."""' in hand_edited
        stand_in = tmp_path / "template_sync.py"
        stand_in.write_text(hand_edited)
        monkeypatch.setattr(gen_sync, "TARGET", stand_in)

        assert gen_sync.main(["--check"]) == 1

        reported = capsys.readouterr().err
        assert '-"""Hand-edited."""' in reported
        assert '+"""Shared sync runner lifecycle template."""' in reported
        assert "Edit template_async.py" in reported

    def test_editing_the_async_template_changes_the_generated_sync_template(self, tmp_path: Path) -> None:
        source = ASYNC_TEMPLATE.read_text()
        before = _generate(source, tmp_path)
        edited = source.replace(
            "        max_iter = max_iterations or self.default_max_iterations\n",
            "        max_iter = max_iterations or self.default_max_iterations  # drift probe\n",
            1,
        )
        assert edited != source, "the anchor line moved; pick another one-line edit"
        after = _generate(edited, tmp_path)
        assert after != before
        assert "# drift probe" in after


class TestTransformRules:
    @pytest.mark.parametrize(
        ("async_source", "expected"),
        [
            ("async def f() -> None:\n    await g()\n", "def f() -> None:\n    g()\n"),
            ("async def f() -> None:\n    async with h() as x:\n        print(x)\n", "def f() -> None:\n    with h() as x:\n        print(x)\n"),
            ("async def f() -> None:\n    async for x in h():\n        print(x)\n", "def f() -> None:\n    for x in h():\n        print(x)\n"),
            ("x = checkpointer.get_run_async(w)\n", "x = sync_cp.get_run(w)\n"),
            ('x = "async"\n', 'x = "sync"\n'),
        ],
    )
    def test_the_token_transform(self, async_source: str, expected: str) -> None:
        assert gen_sync.rewrite_tokens(async_source) == expected

    def test_prose_that_merely_mentions_a_renamed_name_is_left_alone(self) -> None:
        source = '"""A checkpointer is required, and an async run awaits it."""\n'
        assert gen_sync.rewrite_tokens(source) == source

    def test_a_sync_only_block_is_emitted_as_code_and_never_renamed(self) -> None:
        source = (
            "# sync:only-start: the sync half talks to the protocol's sync side\n# checkpointer = self._get_sync_checkpointer(w)\n# sync:only-end\n"
        )
        assert gen_sync.apply_markers(gen_sync.rewrite_tokens(source)) == "checkpointer = self._get_sync_checkpointer(w)\n"


class TestMarkersMustExplainThemselves:
    def test_every_marker_in_the_async_template_carries_a_reason(self) -> None:
        unexplained = [
            line.strip()
            for line in ASYNC_TEMPLATE.read_text().splitlines()
            for marker in (gen_sync.SKIP_LINE, gen_sync.SKIP_START, gen_sync.ONLY_START)
            if marker in line and not line.split(marker, 1)[1].strip()
        ]
        assert unexplained == []

    def test_the_async_template_actually_uses_both_marker_kinds(self) -> None:
        source = ASYNC_TEMPLATE.read_text()
        assert gen_sync.SKIP_START in source
        assert gen_sync.ONLY_START in source

    def test_a_marker_without_a_reason_is_refused(self) -> None:
        with pytest.raises(gen_sync.GenerationError, match="needs a one-line reason"):
            gen_sync.apply_markers("# sync:skip-start:\nx = 1\n# sync:skip-end\n")

    def test_an_unterminated_region_is_refused(self) -> None:
        with pytest.raises(gen_sync.GenerationError, match="unterminated"):
            gen_sync.apply_markers("# sync:skip-start: no end marker\nx = 1\n")

    def test_a_sync_only_body_that_is_not_a_comment_is_refused(self) -> None:
        with pytest.raises(gen_sync.GenerationError, match="bodies must be comments"):
            gen_sync.apply_markers("# sync:only-start: live code by mistake\nx = 1\n# sync:only-end\n")

    def test_a_line_marker_left_on_a_wrapped_statement_is_refused(self) -> None:
        source = "x = f(\n    a=(\n        b\n    ),  # sync:skip: this line closes a paren the next line still needs\n)\n"
        with pytest.raises(gen_sync.GenerationError, match="invalid Python"):
            gen_sync.apply_markers(source)


class TestGeneratedBehaviorIsStillSync:
    def test_the_generated_template_defines_the_sync_class_and_no_coroutines(self) -> None:
        import inspect as _inspect

        from hypergraph.runners._shared.template_sync import SyncRunnerTemplate

        assert not _inspect.iscoroutinefunction(SyncRunnerTemplate.run)
        assert not _inspect.iscoroutinefunction(SyncRunnerTemplate.map)
        assert not _inspect.isasyncgenfunction(SyncRunnerTemplate.map_iter)

    def test_the_sync_template_never_imports_asyncio(self) -> None:
        assert "import asyncio" not in SYNC_TEMPLATE.read_text()

    def test_the_sync_template_keeps_its_protocol_gate(self) -> None:
        from hypergraph.runners._shared.template_sync import SyncRunnerTemplate

        assert hasattr(SyncRunnerTemplate, "_get_sync_checkpointer")
