#!/usr/bin/env python
"""Generate ``template_sync.py`` from ``template_async.py``.

The two runner templates are the same lifecycle written twice. Parity used to be
a checklist item asking a human to read a 1,300-line diff; this script makes it a
machine invariant: the async template is the source of truth and the sync
template is generated from it.

Usage::

    uv run python scripts/gen_sync.py            # rewrite the generated file
    uv run python scripts/gen_sync.py --check    # fail (exit 1) on drift, print the hunk

How the transform works
-----------------------

1. **Markers** (line-based). Every marker carries a reason:

   - ``# sync:skip: <reason>`` as a line suffix drops that one line.
   - ``# sync:skip-start: <reason>`` / ``# sync:skip-end`` drops the region —
     async-only code with no sync counterpart.
   - ``# sync:only-start: <reason>`` / ``# sync:only-end`` wraps a block of
     comments in the async file that are emitted as live code in the sync file.
     This is how the handwritten sync boundary survives generation.

   A marker is a claim that the two halves genuinely differ. Every one that
   exists today traces back to the same constraint: **a sync run must never
   require an event loop** — see ADR 0009
   (``docs/adr/0009-a-sync-run-must-never-require-an-event-loop.md``).

2. **Token rewriting** (``tokenize``-based, so nothing inside a string or a
   comment is ever touched — which is also why it runs *before* the markers:
   a ``sync:only`` body is a comment in the async file and must survive
   verbatim):

   - ``async def`` -> ``def``, ``async with`` -> ``with``, ``async for`` -> ``for``
   - ``await x`` -> ``x``
   - the name table in ``TOKEN_RENAMES`` below (one entry per genuine
     async/sync API difference, each with the reason it exists)
   - the string table in ``STRING_RENAMES`` — the few literals that name the
     family, matched whole so prose is never rewritten

3. **``ruff``** on the result — ``check --fix-only --select I,F401`` then
   ``format`` — so the generated file is byte-stable under the repo's own lint
   job and ``ruff format --check .`` cannot disagree with ``--check`` here.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import io
import shutil
import subprocess
import sys
import tokenize
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "src/hypergraph/runners/_shared/template_async.py"
TARGET = REPO_ROOT / "src/hypergraph/runners/_shared/template_sync.py"

HEADER = """# @generated by scripts/gen_sync.py from template_async.py — DO NOT EDIT.
#
# Edit template_async.py and run `uv run python scripts/gen_sync.py`.
# CI runs `--check` and fails on drift.
"""

# Names that mean one thing in the async template and another in the sync one.
# Every entry is a real API difference, not a stylistic one.
TOKEN_RENAMES: dict[str, str] = {
    # --- the template itself -------------------------------------------------
    "AsyncRunnerTemplate": "SyncRunnerTemplate",
    "AsyncIterator": "Iterator",
    # --- the abstract hooks each runner family implements --------------------
    # Concrete runners already name their halves `_async` / `_sync`; the
    # template only has to agree with them.
    "_execute_graph_impl_async": "_execute_graph_impl",
    "_emit_run_start_async": "_emit_run_start_sync",
    "_emit_run_end_async": "_emit_run_end_sync",
    "_shutdown_dispatcher_async": "_shutdown_dispatcher_sync",
    # --- the exit ladder (#242) ----------------------------------------------
    # Same ladder, two await-shapes; run_teardown.py owns both classes.
    "AsyncRunTeardown": "RunTeardown",
    # --- the event dispatcher ------------------------------------------------
    "emit_async": "emit",
    # --- the checkpointer ----------------------------------------------------
    # A sync run must never require an event loop, so it talks to the
    # SyncCheckpointerProtocol half of the checkpointer. That half predates the
    # async one and is not a suffix rename, hence the explicit table.
    "checkpointer": "sync_cp",
    "fork_workflow_async": "fork_workflow",
    "retry_workflow_async": "retry_workflow",
    "get_run_async": "get_run",
    "get_checkpoint": "checkpoint",
    "get_state": "state",
    "get_steps": "steps",
    "list_runs": "runs",
    "create_run": "create_run_sync",
    "save_step": "save_step_sync",
    "update_run_status": "update_run_status_sync",
    "commit_pause_async": "commit_pause_sync",
    # --- module-level helpers in this file -----------------------------------
    "_get_completed_child_runs": "_get_completed_child_runs_sync",
}

# Exact string-literal tokens to swap. Matching is on the whole token, so prose
# that merely mentions async — a docstring paragraph, an error message — is never
# rewritten; only these exact literals are.
STRING_RENAMES: dict[str, str] = {
    # The runner family reported on inspection payloads and run events.
    '"async"': '"sync"',
    # The checkpointer's raw step reader, looked up by name (see TOKEN_RENAMES).
    '"get_steps"': '"steps"',
    # The two docstrings that name the family they belong to.
    '"""Shared async runner lifecycle template."""': '"""Shared sync runner lifecycle template."""',
    '"""Template implementation for async run/map lifecycle."""': '"""Template implementation for sync run/map lifecycle."""',
}

# Keyword tokens dropped along with the whitespace that follows them.
DROPPED_KEYWORDS = frozenset({"async", "await"})

SKIP_LINE = "# sync:skip:"
SKIP_START = "# sync:skip-start:"
SKIP_END = "# sync:skip-end"
ONLY_START = "# sync:only-start:"
ONLY_END = "# sync:only-end"


class GenerationError(Exception):
    """The async template cannot be transformed as written."""


@dataclass(frozen=True)
class _Replacement:
    row: int  # 1-based, as tokenize reports
    start_col: int
    end_col: int
    text: str


def _reason_of(line: str, marker: str) -> str:
    """Return the reason trailing a marker, or raise if it is missing."""
    reason = line.split(marker, 1)[1].strip()
    if not reason:
        raise GenerationError(f"marker `{marker}` needs a one-line reason: {line.strip()!r}")
    return reason


def apply_markers(source: str) -> str:
    """Resolve ``sync:skip`` / ``sync:only`` regions into plain Python."""
    out: list[str] = []
    mode: str | None = None
    opened_at = 0
    for lineno, line in enumerate(source.splitlines(keepends=True), start=1):
        stripped = line.strip()
        if stripped.startswith(SKIP_START):
            if mode is not None:
                raise GenerationError(f"line {lineno}: `{SKIP_START}` inside an open `{mode}` region (opened at line {opened_at})")
            _reason_of(stripped, SKIP_START)
            mode, opened_at = SKIP_START, lineno
            continue
        if stripped.startswith(ONLY_START):
            if mode is not None:
                raise GenerationError(f"line {lineno}: `{ONLY_START}` inside an open `{mode}` region (opened at line {opened_at})")
            _reason_of(stripped, ONLY_START)
            mode, opened_at = ONLY_START, lineno
            continue
        if stripped == SKIP_END:
            if mode != SKIP_START:
                raise GenerationError(f"line {lineno}: `{SKIP_END}` with no open `{SKIP_START}` region")
            mode = None
            continue
        if stripped == ONLY_END:
            if mode != ONLY_START:
                raise GenerationError(f"line {lineno}: `{ONLY_END}` with no open `{ONLY_START}` region")
            mode = None
            continue

        if mode == SKIP_START:
            continue
        if mode == ONLY_START:
            out.append(_uncomment(line, lineno))
            continue
        if SKIP_LINE in line:
            _reason_of(line, SKIP_LINE)
            continue
        out.append(line)

    if mode is not None:
        raise GenerationError(f"unterminated `{mode}` region opened at line {opened_at}")

    result = "".join(out)
    try:
        ast.parse(result)
    except SyntaxError as error:
        offending = (error.text or "").rstrip()
        raise GenerationError(
            f"the markers leave invalid Python at generated line {error.lineno}: {error.msg}\n"
            f"    {offending}\n"
            f"A `{SKIP_LINE}` suffix drops ONE physical line, so it cannot mark a statement "
            f"`ruff format` has wrapped across several — use `{SKIP_START}` / `{SKIP_END}` there."
        ) from error
    return result


def _uncomment(line: str, lineno: int) -> str:
    """Turn one ``# sync:only`` body line back into code."""
    indent = line[: len(line) - len(line.lstrip())]
    body = line.strip()
    if not body:
        return "\n"
    if not body.startswith("#"):
        raise GenerationError(f"line {lineno}: `{ONLY_START}` bodies must be comments, got {body!r}")
    body = body[1:]
    if body.startswith(" "):
        body = body[1:]
    return f"{indent}{body}\n" if body else "\n"


def rewrite_tokens(source: str) -> str:
    """Apply the async->sync token transform, leaving strings and layout alone."""
    lines = source.splitlines(keepends=True)
    replacements: list[_Replacement] = []
    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    for index, token in enumerate(tokens):
        if token.type == tokenize.NAME and token.string in DROPPED_KEYWORDS:
            following = tokens[index + 1]
            if following.start[0] != token.start[0]:
                raise GenerationError(f"line {token.start[0]}: `{token.string}` is the last token on its line; the rewriter cannot join lines")
            replacements.append(_Replacement(token.start[0], token.start[1], following.start[1], ""))
        elif token.type == tokenize.NAME and token.string in TOKEN_RENAMES:
            replacements.append(_Replacement(token.start[0], token.start[1], token.end[1], TOKEN_RENAMES[token.string]))
        elif token.type == tokenize.STRING and token.string in STRING_RENAMES:
            replacements.append(_Replacement(token.start[0], token.start[1], token.end[1], STRING_RENAMES[token.string]))

    for replacement in sorted(replacements, key=lambda r: (r.row, r.start_col), reverse=True):
        line = lines[replacement.row - 1]
        lines[replacement.row - 1] = line[: replacement.start_col] + replacement.text + line[replacement.end_col :]
    return "".join(lines)


def _ruff(source: str, filename: Path, *args: str) -> str:
    """Pipe ``source`` through the repo's own ruff so the output is byte-stable."""
    executable = shutil.which("ruff")
    command = [executable] if executable else [sys.executable, "-m", "ruff"]
    result = subprocess.run(
        [*command, *args, "--stdin-filename", str(filename), "-"],
        input=source,
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    if result.returncode not in (0, 1):
        raise GenerationError(f"`ruff {' '.join(args)}` rejected the generated file:\n{result.stderr or result.stdout}")
    return result.stdout


def _tidy(source: str, filename: Path) -> str:
    """Sort imports, drop the ones only the async half used, then format.

    Two rules earn their place here and no others. ``I`` because renaming
    ``AsyncRunTeardown`` to ``RunTeardown`` moves it in its import list, and
    ``F401`` because an import whose only user sits in a ``sync:skip`` region is
    unused by construction — marking every such import by hand would double the
    marker count without saying anything the transform does not already know.
    """
    source = _ruff(source, filename, "check", "--fix-only", "--select", "I,F401")
    return _ruff(source, filename, "format")


def _display(path: Path) -> str:
    """Name a path the way a reader of the CI log wants to see it."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def generate(source_path: Path = SOURCE, target_path: Path = TARGET) -> str:
    """Return the sync template that ``source_path`` generates."""
    source = source_path.read_text()
    # Token rewriting runs FIRST, on the async file exactly as committed: the
    # `sync:only` bodies are comments at that point, so the rename table never
    # touches them. They are already written in the sync vocabulary.
    body = apply_markers(rewrite_tokens(source))
    return _tidy(HEADER + body, target_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail on drift instead of rewriting the generated file")
    args = parser.parse_args(argv)

    try:
        expected = generate()
    except GenerationError as error:
        print(f"gen_sync: {error}", file=sys.stderr)
        return 2

    if not args.check:
        TARGET.write_text(expected)
        return 0

    actual = TARGET.read_text() if TARGET.exists() else ""
    if actual == expected:
        return 0
    name = _display(TARGET)
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{name} (committed)",
        tofile=f"{name} (generated)",
    )
    sys.stderr.writelines(diff)
    print(
        f"\ngen_sync: {name} does not match what template_async.py generates.\nEdit template_async.py, then run `uv run python scripts/gen_sync.py`.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
