#!/usr/bin/env python
"""Generate ``template_sync.py`` from ``template_async.py``.

The two runner templates are the same lifecycle written twice. Parity used to be
a checklist item asking a human to read a 1,300-line diff; this script makes it a
machine invariant: the async template is the source of truth and the sync
template is generated from it.

Usage::

    uv run python scripts/gen_sync.py            # rewrite the generated file
    uv run python scripts/gen_sync.py --check    # fail (exit 1) on drift, print the hunk

How the transform works
-----------------------

1. **Markers**, found as COMMENT tokens so prose that merely quotes one is never
   honoured (it is refused instead). Every marker carries a reason:

   - ``# sync:skip: <reason>`` as a line suffix drops that one line.
   - ``# sync:skip-start: <reason>`` / ``# sync:skip-end`` drops the region —
     async-only code with no sync counterpart.
   - ``# sync:only-start: <reason>`` / ``# sync:only-end`` wraps a block of
     comments in the async file that are emitted as live code in the sync file.
     This is how the handwritten sync boundary survives generation.

   A marker is a claim that the two halves genuinely differ. Every one that
   exists today traces back to the same constraint: **a sync run must never
   require an event loop** — see ADR 0009
   (``docs/adr/0009-a-sync-run-must-never-require-an-event-loop.md``).

2. **Token rewriting** (``tokenize``-based, so nothing inside a string or a
   comment is ever touched — which is also why it runs *before* the markers:
   a ``sync:only`` body is a comment in the async file and must survive
   verbatim):

   - ``async def`` -> ``def``, ``async with`` -> ``with``, ``async for`` -> ``for``
   - ``await x`` -> ``x``
   - the name table in ``TOKEN_RENAMES`` below (one entry per genuine
     async/sync API difference, each with the reason it exists). A name from
     that table written as a keyword argument — ``f(checkpointer=x)`` — is
     *refused* rather than rewritten: that name belongs to the callee's
     signature, which this transform does not resolve. Pass it positionally.
   - the string table in ``STRING_RENAMES`` — the few literals that name the
     family, matched whole so prose is never rewritten

   The transform never reaches inside an f-string's replacement fields. What a
   token *is* in there changed in 3.12 (PEP 701: the interior is tokenized, so
   replacement fields become real ``NAME`` tokens and literal parts become
   ``FSTRING_MIDDLE`` rather than one opaque ``STRING``), so a rename-table
   name, an ``await``, a renamed literal, or a marker written inside one is
   *refused* on every interpreter rather than resolved differently on each.

3. **``ruff``** on the result — ``check --fix-only --select I,F401`` then
   ``format`` — so the generated file is byte-stable under the repo's own lint
   job and ``ruff format --check .`` cannot disagree with ``--check`` here. ruff
   is proved present before step 1 runs: a generated file's failure mode must be
   a loud exit, never a shorter file.

Nothing reaches disk that does not compile or that is no longer than the header.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import io
import shutil
import subprocess
import sys
import tokenize
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "src/hypergraph/runners/_shared/template_async.py"
TARGET = REPO_ROOT / "src/hypergraph/runners/_shared/template_sync.py"

HEADER = """# @generated by scripts/gen_sync.py from template_async.py — DO NOT EDIT.
#
# Edit template_async.py and run `uv run python scripts/gen_sync.py`.
# A pre-commit hook and CI both run `--check` and fail on drift.
"""

# Names that mean one thing in the async template and another in the sync one.
# Every entry is a real API difference, not a stylistic one.
TOKEN_RENAMES: dict[str, str] = {
    # --- the template itself -------------------------------------------------
    "AsyncRunnerTemplate": "SyncRunnerTemplate",
    "AsyncIterator": "Iterator",
    # --- the abstract hooks each runner family implements --------------------
    # Concrete runners already name their halves `_async` / `_sync`; the
    # template only has to agree with them.
    "_execute_graph_impl_async": "_execute_graph_impl",
    "_emit_run_start_async": "_emit_run_start_sync",
    "_emit_run_end_async": "_emit_run_end_sync",
    "_shutdown_dispatcher_async": "_shutdown_dispatcher_sync",
    # --- the exit ladder (#242) ----------------------------------------------
    # Same ladder, two await-shapes; run_teardown.py owns both classes.
    "AsyncRunTeardown": "RunTeardown",
    # --- the event dispatcher ------------------------------------------------
    "emit_async": "emit",
    # --- the checkpointer ----------------------------------------------------
    # A sync run must never require an event loop, so it talks to the
    # SyncCheckpointerProtocol half of the checkpointer. That half predates the
    # async one and is not a suffix rename, hence the explicit table.
    "checkpointer": "sync_cp",
    "fork_workflow_async": "fork_workflow",
    "retry_workflow_async": "retry_workflow",
    "get_run_async": "get_run",
    "get_checkpoint": "checkpoint",
    "get_state": "state",
    "get_steps": "steps",
    "list_runs": "runs",
    "create_run": "create_run_sync",
    "save_step": "save_step_sync",
    "update_run_status": "update_run_status_sync",
    "commit_pause_async": "commit_pause_sync",
    # --- module-level helpers in this file -----------------------------------
    "_get_completed_child_runs": "_get_completed_child_runs_sync",
}

# Exact string-literal tokens to swap. Matching is on the whole token, so prose
# that merely mentions async — a docstring paragraph, an error message — is never
# rewritten; only these exact literals are.
STRING_RENAMES: dict[str, str] = {
    # The runner family reported on inspection payloads and run events.
    '"async"': '"sync"',
    # The checkpointer's raw step reader, looked up by name (see TOKEN_RENAMES).
    '"get_steps"': '"steps"',
    # The two docstrings that name the family they belong to.
    '"""Shared async runner lifecycle template."""': '"""Shared sync runner lifecycle template."""',
    '"""Template implementation for async run/map lifecycle."""': '"""Template implementation for sync run/map lifecycle."""',
}

# Keyword tokens dropped along with the whitespace that follows them.
DROPPED_KEYWORDS = frozenset({"async", "await"})

SKIP_LINE = "# sync:skip:"
SKIP_START = "# sync:skip-start:"
SKIP_END = "# sync:skip-end"
ONLY_START = "# sync:only-start:"
ONLY_END = "# sync:only-end"


class GenerationError(Exception):
    """The async template cannot be transformed as written."""


@dataclass(frozen=True)
class _Replacement:
    row: int  # 1-based, as tokenize reports
    start_col: int
    end_col: int
    text: str


def _reason_of(line: str, marker: str) -> str:
    """Return the reason trailing a marker, or raise if it is missing."""
    reason = line.split(marker, 1)[1].strip()
    if not reason:
        raise GenerationError(f"marker `{marker}` needs a one-line reason: {line.strip()!r}")
    return reason


ALL_MARKERS = (SKIP_START, SKIP_END, ONLY_START, ONLY_END, SKIP_LINE)


def _marker_inside_a_string(lineno: int, marker: str) -> GenerationError:
    """The one refusal for a marker that is text rather than a comment.

    Two detectors raise it and one wording is maintained: the ``STRING`` token
    branch, which sees every plain literal, and the ``ast.JoinedStr`` one, which
    sees an f-string's literal parts — those stopped being ``STRING`` tokens in
    3.12.
    """
    return GenerationError(
        f"line {lineno}: `{marker}` appears inside a string literal, "
        f"where it is text and not a marker. The generator refuses it rather "
        f"than silently honouring or silently ignoring it; if the prose has to "
        f"name the marker, break the literal (e.g. '# sync' ':skip:')."
    )


def find_markers(source: str) -> dict[int, str]:
    """Map line number -> the marker comment on it, tokenizing to find them.

    Markers are only ever comments. Scanning lines as text would also honour one
    that happens to appear inside a docstring or a string literal — and now that
    ``dev/CONTRIBUTING.md`` teaches contributors this vocabulary, prose that
    mentions a marker is a matter of time. So detection reads COMMENT tokens,
    and a marker found inside a STRING token is a loud error rather than a
    silently dropped line.

    The STRING token branch stops seeing f-strings in 3.12, where their literal
    parts become ``FSTRING_MIDDLE`` (PEP 701), so a second pass reads the same
    literal parts off the AST. Both passes are needed and neither replaces the
    other: implicit concatenation — the escape hatch the refusal itself
    advertises, ``'# sync' ':skip:'`` — is two STRING tokens holding no whole
    marker between them, but one ``ast.Constant`` that holds one.
    """
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
        tree = ast.parse(source)
    except (SyntaxError, tokenize.TokenError) as error:
        raise GenerationError(f"the async template does not tokenize or parse: {error}") from error

    markers: dict[int, str] = {}
    for token in tokens:
        if token.type == tokenize.COMMENT:
            text = token.string.strip()
            if text.startswith(ALL_MARKERS):
                if token.start[0] in markers:
                    raise GenerationError(f"line {token.start[0]}: two markers on one line")
                markers[token.start[0]] = text
        elif token.type == tokenize.STRING:
            for marker in ALL_MARKERS:
                if marker in token.string:
                    raise _marker_inside_a_string(token.start[0], marker)

    for joined in ast.walk(tree):
        if not isinstance(joined, ast.JoinedStr):
            continue
        # Only the literal parts. A string written *inside* a replacement field
        # is a STRING token in its own right on every interpreter, so the loop
        # above already sees the markers it holds.
        for part in joined.values:
            if isinstance(part, ast.Constant) and isinstance(part.value, str):
                for marker in ALL_MARKERS:
                    if marker in part.value:
                        raise _marker_inside_a_string(joined.lineno, marker)
    return markers


def apply_markers(source: str) -> str:
    """Resolve ``sync:skip`` / ``sync:only`` regions into plain Python."""
    markers = find_markers(source)
    out: list[str] = []
    mode: str | None = None
    opened_at = 0
    for lineno, line in enumerate(source.splitlines(keepends=True), start=1):
        marker = markers.get(lineno, "")
        if marker.startswith((SKIP_START, SKIP_END, ONLY_START, ONLY_END)) and not line.lstrip().startswith("#"):
            raise GenerationError(
                f"line {lineno}: a region marker owns its line — it cannot trail code, "
                f"because resolving the region would drop that code too: {line.strip()!r}"
            )
        if marker.startswith(SKIP_START):
            if mode is not None:
                raise GenerationError(f"line {lineno}: `{SKIP_START}` inside an open `{mode}` region (opened at line {opened_at})")
            _reason_of(marker, SKIP_START)
            mode, opened_at = SKIP_START, lineno
            continue
        if marker.startswith(ONLY_START):
            if mode is not None:
                raise GenerationError(f"line {lineno}: `{ONLY_START}` inside an open `{mode}` region (opened at line {opened_at})")
            _reason_of(marker, ONLY_START)
            mode, opened_at = ONLY_START, lineno
            continue
        if marker == SKIP_END:
            if mode != SKIP_START:
                raise GenerationError(f"line {lineno}: `{SKIP_END}` with no open `{SKIP_START}` region")
            mode = None
            continue
        if marker == ONLY_END:
            if mode != ONLY_START:
                raise GenerationError(f"line {lineno}: `{ONLY_END}` with no open `{ONLY_START}` region")
            mode = None
            continue

        if mode == SKIP_START:
            continue
        if mode == ONLY_START:
            out.append(_uncomment(line, lineno))
            continue
        if marker.startswith(SKIP_LINE):
            _reason_of(marker, SKIP_LINE)
            continue
        out.append(line)

    if mode is not None:
        raise GenerationError(f"unterminated `{mode}` region opened at line {opened_at}")

    result = "".join(out)
    try:
        compile(result, "template_sync.py", "exec")
    except SyntaxError as error:
        offending = (error.text or "").rstrip()
        raise GenerationError(
            f"the markers leave invalid Python at generated line {error.lineno}: {error.msg}\n"
            f"    {offending}\n"
            f"A `{SKIP_LINE}` suffix drops ONE physical line, so it cannot mark a statement "
            f"`ruff format` has wrapped across several — use `{SKIP_START}` / `{SKIP_END}` there."
        ) from error
    return result


def _uncomment(line: str, lineno: int) -> str:
    """Turn one ``# sync:only`` body line back into code."""
    indent = line[: len(line) - len(line.lstrip())]
    body = line.strip()
    if not body:
        return "\n"
    if not body.startswith("#"):
        raise GenerationError(f"line {lineno}: `{ONLY_START}` bodies must be comments, got {body!r}")
    body = body[1:]
    if body.startswith(" "):
        body = body[1:]
    return f"{indent}{body}\n" if body else "\n"


def _keyword_argument_targets(source: str) -> dict[tuple[int, int], str]:
    """Map ``(row, col)`` -> arg name, for every ``name=`` written at a call site.

    A keyword-argument target is the only identifier in the file that names a
    *parameter of something else*. ``tokenize`` cannot tell it apart from any
    other NAME, so the position of every ``ast.keyword`` is collected here and
    matched against the token that starts there.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError as error:
        raise GenerationError(f"the async template does not parse: {error}") from error

    targets: dict[tuple[int, int], str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            for keyword in node.keywords:
                # `**kwargs` has no name to rewrite, and a def parameter's
                # default is not an `ast.keyword` at all — both stay renameable.
                if keyword.arg is not None:
                    targets[(keyword.lineno, keyword.col_offset)] = keyword.arg
    return targets


def _f_string_hazards(source: str) -> list[str]:
    """Name everything inside an f-string replacement field this transform touches.

    Before Python 3.12 an f-string is one opaque ``tokenize.STRING``; from 3.12
    (PEP 701) its interior is tokenized, so a replacement field holds real
    ``NAME`` tokens and the literal parts hold ``FSTRING_MIDDLE``. Every pass in
    this file keys on exactly those token types, so a construct the transform
    acts on written inside a replacement field would make the generated file a
    function of the interpreter that ran the generator. Rather than pick one
    interpreter's semantics and emulate it on the other — for a construct the
    template does not use — it is refused on all of them.

    Only the replacement fields are hazards. An f-string's *literal* part is
    never rewritten on either interpreter, so including it would be a false
    refusal: ``f"async"`` is not ``"async"``.

    Reports every hazard in source order; the caller names the first. Line
    numbers are the f-string's own, which every interpreter agrees on.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError as error:
        raise GenerationError(f"the async template does not parse: {error}") from error

    renamed_literals = {ast.literal_eval(literal) for literal in STRING_RENAMES}
    hazards: list[str] = []
    for joined in ast.walk(tree):
        if not isinstance(joined, ast.JoinedStr):
            continue
        for field in joined.values:
            if not isinstance(field, ast.FormattedValue):
                continue
            for node in ast.walk(field):
                what: str | None = None
                if isinstance(node, ast.Await):
                    what = "await"
                elif isinstance(node, ast.Name) and node.id in TOKEN_RENAMES:
                    what = f"name {node.id}"
                elif isinstance(node, ast.Attribute) and node.attr in TOKEN_RENAMES:
                    what = f"attribute .{node.attr}"
                elif isinstance(node, ast.keyword) and node.arg in TOKEN_RENAMES:
                    what = f"keyword {node.arg}="
                elif isinstance(node, ast.arg) and node.arg in TOKEN_RENAMES:
                    what = f"parameter {node.arg}"
                elif isinstance(node, ast.Constant) and isinstance(node.value, str) and node.value in renamed_literals:
                    what = f"literal {node.value!r}"
                if what is not None:
                    hazards.append(f"line {joined.lineno}: `{what}`")
    return hazards


def rewrite_tokens(source: str) -> str:
    """Apply the async->sync token transform, leaving strings and layout alone."""
    hazards = _f_string_hazards(source)
    if hazards:
        raise GenerationError(
            f"{hazards[0]} sits inside an f-string. Before Python 3.12 an f-string is one "
            f"opaque token and after it is not (PEP 701), so the transform's result would "
            f"depend on the interpreter that ran it. Move it out of the f-string — assign it "
            f"to a local first — or, for prose, use a plain string."
        )
    lines = source.splitlines(keepends=True)
    kwarg_targets = _keyword_argument_targets(source)
    replacements: list[_Replacement] = []
    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    for index, token in enumerate(tokens):
        if token.type == tokenize.NAME and token.string in DROPPED_KEYWORDS:
            following = tokens[index + 1]
            if following.start[0] != token.start[0]:
                raise GenerationError(f"line {token.start[0]}: `{token.string}` is the last token on its line; the rewriter cannot join lines")
            replacements.append(_Replacement(token.start[0], token.start[1], following.start[1], ""))
        elif token.type == tokenize.NAME and token.string in TOKEN_RENAMES:
            if kwarg_targets.get(token.start) == token.string:
                raise GenerationError(
                    f"line {token.start[0]}: `{token.string}=` is a keyword argument whose name is in "
                    f"the rename table. The generator rewrites names, not the signatures they bind to, "
                    f"so it cannot know whether the callee's parameter is renamed too. Pass it "
                    f"positionally, or choose a different name."
                )
            replacements.append(_Replacement(token.start[0], token.start[1], token.end[1], TOKEN_RENAMES[token.string]))
        elif token.type == tokenize.STRING and token.string in STRING_RENAMES:
            replacements.append(_Replacement(token.start[0], token.start[1], token.end[1], STRING_RENAMES[token.string]))

    for replacement in sorted(replacements, key=lambda r: (r.row, r.start_col), reverse=True):
        line = lines[replacement.row - 1]
        lines[replacement.row - 1] = line[: replacement.start_col] + replacement.text + line[replacement.end_col :]
    return "".join(lines)


def ruff_command() -> list[str]:
    """Resolve a working ruff, or say so before anything is written.

    A ruff that is merely absent used to look like a ruff that formatted the
    file into nothing: ``python -m ruff`` exits 1 with empty stdout when the
    module is missing, which is indistinguishable from "no findings" — and the
    caller would then write an empty ``template_sync.py`` and exit 0. So the
    executable is resolved and *proved* (``--version``) before generation runs.
    """
    executable = shutil.which("ruff")
    candidates = [[executable]] if executable else []
    candidates.append([sys.executable, "-m", "ruff"])
    for command in candidates:
        try:
            probe = subprocess.run([*command, "--version"], capture_output=True, text=True, cwd=REPO_ROOT)
        except OSError:
            continue
        if probe.returncode == 0:
            return command
    raise GenerationError(
        "ruff is not available, and the generated file is formatted by it — refusing to write "
        "anything rather than emit an unformatted or empty template. Run this through the "
        "project environment: `uv run python scripts/gen_sync.py`."
    )


def _ruff(source: str, filename: Path, command: list[str], *args: str) -> str:
    """Pipe ``source`` through the repo's own ruff so the output is byte-stable."""
    result = subprocess.run(
        [*command, *args, "--stdin-filename", str(filename), "-"],
        input=source,
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    # ruff check exits 1 when it reports findings it could not fix; that is not a
    # failure of the run and stdout still holds the fixed source. Anything else is.
    if result.returncode not in (0, 1):
        raise GenerationError(f"`ruff {' '.join(args)}` rejected the generated file:\n{result.stderr or result.stdout}")
    if not result.stdout.strip():
        raise GenerationError(f"`ruff {' '.join(args)}` returned nothing; refusing to write an empty template.\n{result.stderr}")
    return result.stdout


def _tidy(source: str, filename: Path) -> str:
    """Sort imports, drop the ones only the async half used, then format.

    Two rules earn their place here and no others. ``I`` because renaming
    ``AsyncRunTeardown`` to ``RunTeardown`` moves it in its import list, and
    ``F401`` because an import whose only user sits in a ``sync:skip`` region is
    unused by construction — marking every such import by hand would double the
    marker count without saying anything the transform does not already know.
    """
    command = ruff_command()
    source = _ruff(source, filename, command, "check", "--fix-only", "--select", "I,F401")
    return _ruff(source, filename, command, "format")


def _display(path: Path) -> str:
    """Name a path the way a reader of the CI log wants to see it."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def generate(source_path: Path = SOURCE, target_path: Path = TARGET) -> str:
    """Return the sync template that ``source_path`` generates."""
    source = source_path.read_text()
    # Token rewriting runs FIRST, on the async file exactly as committed: the
    # `sync:only` bodies are comments at that point, so the rename table never
    # touches them. They are already written in the sync vocabulary.
    body = apply_markers(rewrite_tokens(source))
    return _checked(_tidy(HEADER + body, target_path))


def _checked(generated: str) -> str:
    """Last gate before anything is written or compared.

    Everything upstream of here can be wrong in a way that produces *less* text
    rather than an exception — a ruff that is not there, a transform that ate the
    file. A generated template that is not valid Python, or that is barely longer
    than its own header, is never what the author meant, so it never reaches disk.

    The gate is ``compile``, not ``ast.parse``, because this transform's
    characteristic failure is a rewrite miss that leaves ``await`` in a plain
    ``def`` — and ``ast.parse`` accepts that, as it accepts ``async for`` /
    ``async with`` in a plain ``def`` and ``yield from`` in an ``async def``.
    Only the symbol-table pass ``compile`` runs rejects them, so with
    ``ast.parse`` the broken template reached disk and failed at import instead.
    """
    if len(generated) <= len(HEADER) + 1:
        raise GenerationError(f"the transform produced {len(generated)} bytes, which is no more than the header; refusing to write it")
    try:
        compile(generated, "template_sync.py", "exec")
    except SyntaxError as error:
        raise GenerationError(f"the generated template is not valid Python at line {error.lineno}: {error.msg}") from error
    return generated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail on drift instead of rewriting the generated file")
    args = parser.parse_args(argv)

    try:
        expected = generate()
    except GenerationError as error:
        print(f"gen_sync: {error}", file=sys.stderr)
        return 2

    if not args.check:
        TARGET.write_text(expected)
        return 0

    actual = TARGET.read_text() if TARGET.exists() else ""
    if actual == expected:
        return 0
    name = _display(TARGET)
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{name} (committed)",
        tofile=f"{name} (generated)",
    )
    sys.stderr.writelines(diff)
    print(
        f"\ngen_sync: {name} does not match what template_async.py generates.\nEdit template_async.py, then run `uv run python scripts/gen_sync.py`.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
