"""Hypergraph - A hierarchical and modular graph workflow framework."""

from hypergraph._repr import get_display_mode, set_display_mode
from hypergraph.cache import CacheBackend, DiskCache, InMemoryCache
from hypergraph.checkpointers import (
    AnswerRejectedError,
    Checkpointer,
    CheckpointPolicy,
    PauseAlreadySettledError,
    PauseSettlementError,
    PauseSlot,
    SqliteCheckpointer,
    StalePauseError,
)
from hypergraph.diagnostics import (
    Diagnostic,
    DiagnosticContext,
    DiagnosticFix,
    DiagnosticLocation,
)
from hypergraph.events import (
    AsyncEventProcessor,
    BaseEvent,
    CacheHitEvent,
    Event,
    EventDispatcher,
    EventProcessor,
    InnerCacheEvent,
    InterruptEvent,
    NodeAttemptEndEvent,
    NodeAttemptStartEvent,
    NodeEndEvent,
    NodeErrorEvent,
    NodeStartEvent,
    RouteDecisionEvent,
    RunEndEvent,
    RunStartEvent,
    StopRequestedEvent,
    StreamingChunkEvent,
    SuperstepStartEvent,
    TypedEventProcessor,
)
from hypergraph.events.console import ConsoleProcessor, LiveConsole, render_console
from hypergraph.events.rich_progress import RichProgressProcessor
from hypergraph.exceptions import (
    AttemptOutcomeUnknownError,
    AttemptTimeoutError,
    CheckpointCoercionError,
    CompactedRetentionError,
    ExecutionError,
    GraphChangedError,
    IncompatibleRunnerError,
    InfiniteLoopError,
    InputOverrideRequiresForkError,
    MissingInputError,
    RetryPolicyChangedError,
    RetryWindowExpiredError,
    WorkflowAlreadyCompletedError,
    WorkflowAlreadyRunningError,
    WorkflowForkError,
    WorkflowStoppedError,
    get_failure_evidence,
)
from hypergraph.graph import Graph, GraphConfigError, InputSpec
from hypergraph.host import (
    RUN_READ_STATUS_VALUES,
    AlreadyTerminalError,
    BatchCommandReceipt,
    BatchItemReadModel,
    BatchItemView,
    BatchReadModel,
    BatchRef,
    BatchSubmitReceipt,
    BatchSummaryReadModel,
    BatchTolerance,
    BatchUpdate,
    BatchView,
    BuilderIdentityError,
    CommandReceipt,
    ConsolePanel,
    DefinitionId,
    FollowDeadlineExpired,
    ForkCompatibilityError,
    GraphBuilder,
    Host,
    HostError,
    HostRuntime,
    ItemKeyError,
    NodeTimingReadModel,
    NodeTimingsReadModel,
    NoServingWorkerError,
    PauseReadModel,
    RerunError,
    RunHome,
    RunHomeClient,
    RunHomeReadModel,
    RunQuery,
    RunReadModel,
    RunRef,
    RunTimingReadModel,
    RunUpdate,
    RunView,
    StepTimingReadModel,
    SubmissionProgress,
    SubmissionWatcher,
    SubmitReceipt,
    UnservedGraphError,
    WaitingCondition,
    WatchSnapshot,
    WorkerCoverage,
    WorkflowIdConflictError,
    serve,
    watch_submissions,
)
from hypergraph.host import (
    # Retired by ADR 0006 and raised by nothing. Imported — so an existing
    # ``except hypergraph.WorkerLockError`` still resolves for its one
    # deprecation release — but deliberately absent from ``__all__``: a star
    # import must not hand out a name that can never fire. Its documented door
    # is ``hypergraph.host``.
    WorkerLockError as WorkerLockError,
)
from hypergraph.limits import ProcessLocalLimiter
from hypergraph.nodes import (
    END,
    FunctionNode,
    GateNode,
    GraphNode,
    GraphNodeMapExecutionConfig,
    HyperNode,
    IfElseNode,
    InterruptNode,
    RenameError,
    RetryAfterError,
    RetryPolicy,
    RouteNode,
    ifelse,
    interrupt,
    node,
    route,
)
from hypergraph.runners import (
    AsyncHandle,
    AsyncRunner,
    BaseRunner,
    DaftRunner,
    ErrorHandling,
    FailureEvidence,
    InspectionDisplay,
    MapLog,
    MapResult,
    NodeContext,
    NodeRecord,
    NodeSpanRef,
    NodeStats,
    PauseInfo,
    RunLog,
    RunResult,
    RunStatus,
    SyncHandle,
    SyncRunner,
    current_node_span,
)

__all__ = [
    # Decorators and node types
    "node",
    "ifelse",
    "route",
    "interrupt",
    "FunctionNode",
    "GraphNode",
    "GraphNodeMapExecutionConfig",
    "GateNode",
    "IfElseNode",
    "RouteNode",
    "InterruptNode",
    "HyperNode",
    "END",
    "RetryPolicy",
    "RetryAfterError",
    # Provider-resource admission (never the host active-Run cap)
    "ProcessLocalLimiter",
    # Graph
    "Graph",
    "InputSpec",
    # Runners
    "SyncHandle",
    "AsyncHandle",
    "SyncRunner",
    "AsyncRunner",
    "DaftRunner",
    "BaseRunner",
    "ErrorHandling",
    "FailureEvidence",
    "InspectionDisplay",
    "PauseInfo",
    "RunResult",
    "MapResult",
    "RunStatus",
    # Errors
    "RenameError",
    "GraphConfigError",
    "AttemptOutcomeUnknownError",
    "AttemptTimeoutError",
    "RetryWindowExpiredError",
    "CheckpointCoercionError",
    "CompactedRetentionError",
    "MissingInputError",
    "InfiniteLoopError",
    "IncompatibleRunnerError",
    "ExecutionError",
    "get_failure_evidence",
    "WorkflowAlreadyCompletedError",
    "GraphChangedError",
    "RetryPolicyChangedError",
    "WorkflowForkError",
    "InputOverrideRequiresForkError",
    "WorkflowAlreadyRunningError",
    "WorkflowStoppedError",
    # Diagnostics
    "Diagnostic",
    "DiagnosticContext",
    "DiagnosticFix",
    "DiagnosticLocation",
    # RunLog
    "RunLog",
    "MapLog",
    "NodeRecord",
    "NodeStats",
    # Events
    "BaseEvent",
    "SuperstepStartEvent",
    "Event",
    "EventDispatcher",
    "EventProcessor",
    "AsyncEventProcessor",
    "TypedEventProcessor",
    "InterruptEvent",
    "NodeAttemptEndEvent",
    "NodeAttemptStartEvent",
    "NodeEndEvent",
    "NodeErrorEvent",
    "NodeStartEvent",
    "RouteDecisionEvent",
    "RunEndEvent",
    "RunStartEvent",
    "StopRequestedEvent",
    "CacheHitEvent",
    "InnerCacheEvent",
    "StreamingChunkEvent",
    "RichProgressProcessor",
    "ConsoleProcessor",
    "LiveConsole",
    "render_console",
    # Context
    "NodeContext",
    # Observability
    "NodeSpanRef",
    "current_node_span",
    # Cache
    "CacheBackend",
    "InMemoryCache",
    "DiskCache",
    # Checkpointing
    "Checkpointer",
    "CheckpointPolicy",
    "SqliteCheckpointer",
    # Durable host (Tier 1 local host)
    "serve",
    "ConsolePanel",
    "SubmissionProgress",
    "SubmissionWatcher",
    "WatchSnapshot",
    "watch_submissions",
    "Host",
    "HostRuntime",
    "RunHome",
    "WorkerCoverage",
    "RunHomeClient",
    "RunHomeReadModel",
    "RunRef",
    "SubmitReceipt",
    "CommandReceipt",
    "RunView",
    "RunUpdate",
    "RunQuery",
    "RunReadModel",
    "PauseReadModel",
    "NodeTimingsReadModel",
    "NodeTimingReadModel",
    "RunTimingReadModel",
    "StepTimingReadModel",
    "RUN_READ_STATUS_VALUES",
    "WaitingCondition",
    "HostError",
    "AlreadyTerminalError",
    "DefinitionId",
    "WorkflowIdConflictError",
    "ForkCompatibilityError",
    "FollowDeadlineExpired",
    "RerunError",
    "UnservedGraphError",
    "NoServingWorkerError",
    "BuilderIdentityError",
    "ItemKeyError",
    "GraphBuilder",
    "BatchRef",
    "BatchSubmitReceipt",
    "BatchCommandReceipt",
    "BatchView",
    "BatchItemView",
    "BatchReadModel",
    "BatchItemReadModel",
    "BatchSummaryReadModel",
    "BatchUpdate",
    "BatchTolerance",
    # Durable pause slots (PRD 0010)
    "PauseSlot",
    "PauseSettlementError",
    "AnswerRejectedError",
    "PauseAlreadySettledError",
    "StalePauseError",
    # Display
    "set_display_mode",
    "get_display_mode",
]
