"""Hypergraph - A hierarchical and modular graph workflow framework."""

from hypergraph._repr import get_display_mode, set_display_mode
from hypergraph.cache import CacheBackend, DiskCache, InMemoryCache
from hypergraph.checkpointers import (
    Checkpointer,
    CheckpointPolicy,
    SqliteCheckpointer,
)
from hypergraph.events import (
    AsyncEventProcessor,
    BaseEvent,
    CacheHitEvent,
    Event,
    EventDispatcher,
    EventProcessor,
    InnerCacheEvent,
    InterruptEvent,
    NodeEndEvent,
    NodeErrorEvent,
    NodeStartEvent,
    RouteDecisionEvent,
    RunEndEvent,
    RunStartEvent,
    StopRequestedEvent,
    StreamingChunkEvent,
    SuperstepStartEvent,
    TypedEventProcessor,
)
from hypergraph.events.rich_progress import RichProgressProcessor
from hypergraph.exceptions import (
    AttemptTimeoutError,
    CompactedRetentionError,
    ExecutionError,
    GraphChangedError,
    IncompatibleRunnerError,
    InfiniteLoopError,
    InputOverrideRequiresForkError,
    MissingInputError,
    RetryPolicyChangedError,
    RetryWindowExpiredError,
    WorkflowAlreadyCompletedError,
    WorkflowAlreadyRunningError,
    WorkflowForkError,
    WorkflowStoppedError,
    get_failure_evidence,
)
from hypergraph.graph import Graph, GraphConfigError, InputSpec
from hypergraph.nodes import (
    END,
    FunctionNode,
    GateNode,
    GraphNode,
    GraphNodeMapExecutionConfig,
    HyperNode,
    IfElseNode,
    InterruptNode,
    RenameError,
    RetryAfterError,
    RetryPolicy,
    RouteNode,
    ifelse,
    interrupt,
    node,
    route,
)
from hypergraph.runners import (
    AsyncHandle,
    AsyncRunner,
    BaseRunner,
    DaftRunner,
    ErrorHandling,
    FailureEvidence,
    InspectionDisplay,
    MapLog,
    MapResult,
    NodeRecord,
    NodeStats,
    PauseInfo,
    RunLog,
    RunResult,
    RunStatus,
    SyncHandle,
    SyncRunner,
)
from hypergraph.runners._shared.node_context import NodeContext
from hypergraph.runners._shared.observability import NodeSpanRef, current_node_span

__all__ = [
    # Decorators and node types
    "node",
    "ifelse",
    "route",
    "interrupt",
    "FunctionNode",
    "GraphNode",
    "GraphNodeMapExecutionConfig",
    "GateNode",
    "IfElseNode",
    "RouteNode",
    "InterruptNode",
    "HyperNode",
    "END",
    "RetryPolicy",
    "RetryAfterError",
    # Graph
    "Graph",
    "InputSpec",
    # Runners
    "SyncHandle",
    "AsyncHandle",
    "SyncRunner",
    "AsyncRunner",
    "DaftRunner",
    "BaseRunner",
    "ErrorHandling",
    "FailureEvidence",
    "InspectionDisplay",
    "PauseInfo",
    "RunResult",
    "MapResult",
    "RunStatus",
    # Errors
    "RenameError",
    "GraphConfigError",
    "AttemptTimeoutError",
    "RetryWindowExpiredError",
    "CompactedRetentionError",
    "MissingInputError",
    "InfiniteLoopError",
    "IncompatibleRunnerError",
    "ExecutionError",
    "get_failure_evidence",
    "WorkflowAlreadyCompletedError",
    "GraphChangedError",
    "RetryPolicyChangedError",
    "WorkflowForkError",
    "InputOverrideRequiresForkError",
    "WorkflowAlreadyRunningError",
    "WorkflowStoppedError",
    # RunLog
    "RunLog",
    "MapLog",
    "NodeRecord",
    "NodeStats",
    # Events
    "BaseEvent",
    "SuperstepStartEvent",
    "Event",
    "EventDispatcher",
    "EventProcessor",
    "AsyncEventProcessor",
    "TypedEventProcessor",
    "InterruptEvent",
    "NodeEndEvent",
    "NodeErrorEvent",
    "NodeStartEvent",
    "RouteDecisionEvent",
    "RunEndEvent",
    "RunStartEvent",
    "StopRequestedEvent",
    "CacheHitEvent",
    "InnerCacheEvent",
    "StreamingChunkEvent",
    "RichProgressProcessor",
    # Context
    "NodeContext",
    # Observability
    "NodeSpanRef",
    "current_node_span",
    # Cache
    "CacheBackend",
    "InMemoryCache",
    "DiskCache",
    # Checkpointing
    "Checkpointer",
    "CheckpointPolicy",
    "SqliteCheckpointer",
    # Display
    "set_display_mode",
    "get_display_mode",
]
